### ISSUE TITLE
feature - add code blocks to posts

### ISSUE THREAD

**Issue by richpeers** [laraveluk/website#77]
feature request - ability to wrap code with code blocks in posts

**Comment by simondavies** [comment]
Looking into this, it's using the https://github.com/chmln/vue-wysiwyg package. And looks like this currently does not have the option yet to add a code block option yet.

I have added a feature request to have this added, so if this becomes active then possible coudl be added.

Otherwise switching out for another like https://github.com/davidroyer/vue2-editor or a good one being https://github.com/basecamp/trix also been covered on Laracasts (https://laracasts.com/series/lets-build-a-forum-with-laravel/episodes/99)

**Comment by MadMikeyB** [comment]
@simondavies I like thie idea of using vue2-editor. I'll look into this if everyone is okay with that. Can't assign myself yet.

**Comment by stevepop** [comment]
I already use vue2-editor on another project. I could easily plug it in. I'll give it a go

**Comment by simondavies** [comment]
if its the easiest to sort, as it might be a while for the other repo to respond and/or add.  Especially if you have had experience with it before :-)

**Comment by stevepop** [comment]
This has now been resolved with commit https://github.com/laraveluk/website/pull/95/commits/aa67b337414c1df8c8eebd9371ab86b1ed581972
